### ISSUE TITLE
Testssuite doesn't stop when Ctrl-C is pressed

### ISSUE THREAD

**Issue by yurivict** [Xyce/Xyce_Regression#1]
Ctrl-C only stops the current case and it proceeds to the next one instead of stopping.

Version: 7.5.0
FreeBSD 13.1

**Comment by tvrusso** [comment]
This is known behavior and is due to the way that run_xyce_regression forks subprocesses to run the tests.  A single control-C simply gets the script's attention to kill one subprocess.

Rapidly repeated Control-C will make it stop and ask if you want to abort the run completely.

This is not something the team will likely be fixing.  Sorry.
